/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import javax.swing.JOptionPane;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.HashSet;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicolas
 */
public class Pago extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form Pago
     */
    private String item;
    private String id;

    public Pago(String i) {
        initComponents();
        item = i;

        try {

            PreparedStatement ps;
            String query = "SELECT id_Locacion FROM Locacion WHERE direccion =?";
            ps = myConnection.getConnection().prepareStatement(query);
            ps.setString(1, i);
            rs = ps.executeQuery();
            if (rs.next()) {
                id = rs.getString("id_Locacion");
            }

        } catch (Exception e) {
            // NO ENTRA A LA DB
            e.printStackTrace();
        }

    }

    public void pagar() {

        String desc = jTextField2.getText();
        int pay = Integer.parseInt(jTextField1.getText());
        int location = Integer.parseInt(id);
        System.out.println("1ro");

        try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectLockers;user=Admin;password=Admin")) {
            PreparedStatement pslock;
            String querylock = "INSERT INTO Locker VALUES (?)";
            pslock = myConnection.getConnection().prepareStatement(querylock);
            pslock.setInt(1, 1);
            if (pslock.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Locker Insertado");
            }
        } catch (SQLException e) {
            System.out.println("Error en el primer intento: " + e.getMessage());
        }
    }

     public void pagar2() {

         int location = Integer.parseInt(id);

        try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectLockers;user=Admin;password=Admin")) {
           PreparedStatement psalq;
            String queryalq = "INSERT INTO Alquiler VALUES (?,?,?,?)";
            psalq = myConnection.getConnection().prepareStatement(queryalq);
            psalq.setInt(1, location);
            psalq.setInt(2, 1);
            Date fechaact = new Date();
            java.sql.Date fechasql = new java.sql.Date(fechaact.getTime());
            psalq.setDate(3, fechasql);
            psalq.setDate(4, fechasql);
            if (psalq.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Alquiler insertado");
            }
        } catch (SQLException e) {
            System.out.println("Error en el segundo intento: " + e.getMessage());
        }
    }
     
      public void pagar3() {

         int location = Integer.parseInt(id);
         String desc = jTextField2.getText();
        int pay = Integer.parseInt(jTextField1.getText());

        try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ProjectLockers;user=Admin;password=Admin")) {
          PreparedStatement ps;
                            String query = "INSERT INTO Pago VALUES (?,?)";
                            ps = myConnection.getConnection().prepareStatement(query);
                            ps.setInt(1, pay);
                            ps.setString(2, desc);
                            if( ps.executeUpdate()>0){                           
                                      JOptionPane.showMessageDialog(null, "Pago Realizado");

                            }
        } catch (SQLException e) {
            System.out.println("Error en el segundo intento: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("SALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 180, 30));

        jButton2.setText("HACER OTRO ALQUILER ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 180, 30));

        jButton1.setText("REALIZAR ALQUILER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 150, 70));

        jTextField2.setText("NEQUI");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 230, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de pago");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 180, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Costo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 120, 50));

        jTextField1.setText("4000");
        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pago.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pagar();
        pagar2();
        pagar3();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PanelUser paneluser = new PanelUser();
        paneluser.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String item = null;
                new Pago(item).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
